version: '3.8'
services:
  mongo:
    image: mongo:5.0.7
    environment:
      MONGO_INITDB_ROOT_USERNAME: 3ac
      MONGO_INITDB_ROOT_PASSWORD: 3ac
    ports:
      - 27017:27017
    container_name: mongo
